"""increase_currency_code_length

Revision ID: 39933c6c7c90
Revises: 4034d70d7160
Create Date: 2025-06-12 20:09:06.750037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39933c6c7c90'
down_revision: Union[str, None] = '4034d70d7160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_currencies',
    sa.Column('currency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['dim_countries.country_code'], ),
    sa.PrimaryKeyConstraint('currency_id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('fact_cryptocurrency_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_volume', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('circulating_supply', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('price_change_percentage_24h', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('price_change_percentage_7d', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('price_change_percentage_30d', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('deviation_from_dollar', sa.DECIMAL(precision=12, scale=10), nullable=True),
    sa.Column('within_01_percent', sa.Boolean(), nullable=True),
    sa.Column('within_05_percent', sa.Boolean(), nullable=True),
    sa.Column('within_1_percent', sa.Boolean(), nullable=True),
    sa.Column('price_band', sa.String(length=20), nullable=True),
    sa.Column('rolling_avg_7d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('rolling_avg_30d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('rolling_std_7d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('rolling_std_30d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('volatility_7d', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('volatility_30d', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('market_dominance_percentage', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.date_key'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['dim_financial_instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'record_date', name='uq_crypto_instrument_date')
    )
    op.create_index('idx_crypto_date_instrument', 'fact_cryptocurrency_prices', ['record_date', 'instrument_id'], unique=False)
    op.create_index('idx_crypto_market_cap', 'fact_cryptocurrency_prices', ['record_date', 'market_cap'], unique=False)
    op.create_index('idx_crypto_stablecoin', 'fact_cryptocurrency_prices', ['instrument_id', 'deviation_from_dollar'], unique=False)
    op.create_foreign_key(None, 'dim_financial_instruments', 'dim_currencies', ['primary_currency_code'], ['currency_code'])
    op.create_foreign_key(None, 'dim_financial_instruments', 'dim_currencies', ['secondary_currency_code'], ['currency_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dim_financial_instruments', type_='foreignkey')
    op.drop_constraint(None, 'dim_financial_instruments', type_='foreignkey')
    op.drop_index('idx_crypto_stablecoin', table_name='fact_cryptocurrency_prices')
    op.drop_index('idx_crypto_market_cap', table_name='fact_cryptocurrency_prices')
    op.drop_index('idx_crypto_date_instrument', table_name='fact_cryptocurrency_prices')
    op.drop_table('fact_cryptocurrency_prices')
    op.drop_table('dim_currencies')
    # ### end Alembic commands ###
