"""increase_currency_code_lengths

Revision ID: fa936d71d109
Revises: 39933c6c7c90
Create Date: 2025-06-12 20:10:39.023370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa936d71d109'
down_revision: Union[str, None] = '39933c6c7c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_countries',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('dim_currencies',
    sa.Column('currency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['dim_countries.country_code'], ),
    sa.PrimaryKeyConstraint('currency_id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('dim_financial_instruments',
    sa.Column('instrument_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('instrument_name', sa.String(length=255), nullable=False),
    sa.Column('instrument_code', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('primary_currency_code', sa.String(length=10), nullable=False),
    sa.Column('secondary_currency_code', sa.String(length=10), nullable=True),
    sa.Column('issuer_entity_id', sa.Integer(), nullable=True),
    sa.Column('manager_entity_id', sa.Integer(), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('coingecko_id', sa.String(length=100), nullable=True),
    sa.Column('bloomberg_ticker', sa.String(length=50), nullable=True),
    sa.Column('is_stablecoin', sa.Boolean(), nullable=True),
    sa.Column('is_esg_compliant', sa.Boolean(), nullable=True),
    sa.Column('is_sharia_compliant', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('minimum_investment', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_entity_id'], ['dim_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['manager_entity_id'], ['dim_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['primary_currency_code'], ['dim_currencies.currency_code'], ),
    sa.ForeignKeyConstraint(['secondary_currency_code'], ['dim_currencies.currency_code'], ),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_index('idx_instruments_active_asset_class', 'dim_financial_instruments', ['is_active', 'asset_class', 'instrument_type'], unique=False)
    op.create_index('idx_instruments_active_type', 'dim_financial_instruments', ['is_active', 'instrument_type'], unique=False)
    op.create_index('idx_instruments_asset_class', 'dim_financial_instruments', ['asset_class', 'risk_level'], unique=False)
    op.create_index('idx_instruments_bloomberg', 'dim_financial_instruments', ['bloomberg_ticker'], unique=False)
    op.create_index('idx_instruments_bonds_maturity', 'dim_financial_instruments', ['instrument_type', 'maturity_date'], unique=False)
    op.create_index('idx_instruments_coingecko', 'dim_financial_instruments', ['coingecko_id'], unique=False)
    op.create_index('idx_instruments_currency_asset', 'dim_financial_instruments', ['primary_currency_code', 'asset_class'], unique=False)
    op.create_index('idx_instruments_cusip', 'dim_financial_instruments', ['cusip'], unique=False)
    op.create_index('idx_instruments_esg_compliance', 'dim_financial_instruments', ['is_esg_compliant', 'asset_class'], unique=False)
    op.create_index('idx_instruments_inception', 'dim_financial_instruments', ['inception_date'], unique=False)
    op.create_index('idx_instruments_isin', 'dim_financial_instruments', ['isin'], unique=False)
    op.create_index('idx_instruments_issuer', 'dim_financial_instruments', ['issuer_entity_id'], unique=False)
    op.create_index('idx_instruments_issuer_type', 'dim_financial_instruments', ['issuer_entity_id', 'instrument_type'], unique=False)
    op.create_index('idx_instruments_manager', 'dim_financial_instruments', ['manager_entity_id'], unique=False)
    op.create_index('idx_instruments_maturity', 'dim_financial_instruments', ['maturity_date'], unique=False)
    op.create_index('idx_instruments_stablecoin', 'dim_financial_instruments', ['is_stablecoin'], unique=False)
    op.create_index('idx_instruments_type_currency', 'dim_financial_instruments', ['instrument_type', 'primary_currency_code'], unique=False)
    op.create_table('fact_cryptocurrency_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_volume', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('circulating_supply', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('price_change_percentage_24h', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('price_change_percentage_7d', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('price_change_percentage_30d', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('deviation_from_dollar', sa.DECIMAL(precision=12, scale=10), nullable=True),
    sa.Column('within_01_percent', sa.Boolean(), nullable=True),
    sa.Column('within_05_percent', sa.Boolean(), nullable=True),
    sa.Column('within_1_percent', sa.Boolean(), nullable=True),
    sa.Column('price_band', sa.String(length=20), nullable=True),
    sa.Column('rolling_avg_7d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('rolling_avg_30d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('rolling_std_7d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('rolling_std_30d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('volatility_7d', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('volatility_30d', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('market_dominance_percentage', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.date_key'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['dim_financial_instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'record_date', name='uq_crypto_instrument_date')
    )
    op.create_index('idx_crypto_date_instrument', 'fact_cryptocurrency_prices', ['record_date', 'instrument_id'], unique=False)
    op.create_index('idx_crypto_market_cap', 'fact_cryptocurrency_prices', ['record_date', 'market_cap'], unique=False)
    op.create_index('idx_crypto_stablecoin', 'fact_cryptocurrency_prices', ['instrument_id', 'deviation_from_dollar'], unique=False)
    op.create_table('fact_forex_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('open_rate', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('high_rate', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('low_rate', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('exchange_rate', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('volume', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('dividends', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('stock_splits', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('quote_currency', sa.String(length=3), nullable=True),
    sa.Column('pair', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year_quarter', sa.String(length=10), nullable=True),
    sa.Column('monthly_pct_change', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('yoy_pct_change', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('quarterly_volatility', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('annual_volatility', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('significant_move', sa.Boolean(), nullable=True),
    sa.Column('ma_12_month', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['date_key'], ['dim_dates.date_key'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['dim_financial_instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'record_date', name='uq_forex_instrument_date')
    )
    op.create_index('idx_forex_date_instrument', 'fact_forex_rates', ['record_date', 'instrument_id'], unique=False)
    op.create_index('idx_forex_pair_date', 'fact_forex_rates', ['pair', 'record_date'], unique=False)
    op.create_index('idx_forex_significant_moves', 'fact_forex_rates', ['significant_move', 'record_date'], unique=False)
    op.create_index('idx_forex_volatility', 'fact_forex_rates', ['record_date', 'quarterly_volatility'], unique=False)
    op.create_foreign_key(None, 'dim_entities', 'dim_countries', ['country_code'], ['country_code'])
    op.create_foreign_key(None, 'fact_carbon_offsets', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'fact_etf_performance', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'fact_fixed_deposits', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'fact_green_bonds', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'fact_market_indexes', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'fact_money_market_funds', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    op.create_foreign_key(None, 'fact_treasury_securities', 'dim_financial_instruments', ['instrument_id'], ['instrument_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_treasury_securities', type_='foreignkey')
    op.drop_constraint(None, 'fact_money_market_funds', type_='foreignkey')
    op.drop_constraint(None, 'fact_market_indexes', type_='foreignkey')
    op.drop_constraint(None, 'fact_green_bonds', type_='foreignkey')
    op.drop_constraint(None, 'fact_fixed_deposits', type_='foreignkey')
    op.drop_constraint(None, 'fact_etf_performance', type_='foreignkey')
    op.drop_constraint(None, 'fact_carbon_offsets', type_='foreignkey')
    op.drop_constraint(None, 'dim_entities', type_='foreignkey')
    op.drop_index('idx_forex_volatility', table_name='fact_forex_rates')
    op.drop_index('idx_forex_significant_moves', table_name='fact_forex_rates')
    op.drop_index('idx_forex_pair_date', table_name='fact_forex_rates')
    op.drop_index('idx_forex_date_instrument', table_name='fact_forex_rates')
    op.drop_table('fact_forex_rates')
    op.drop_index('idx_crypto_stablecoin', table_name='fact_cryptocurrency_prices')
    op.drop_index('idx_crypto_market_cap', table_name='fact_cryptocurrency_prices')
    op.drop_index('idx_crypto_date_instrument', table_name='fact_cryptocurrency_prices')
    op.drop_table('fact_cryptocurrency_prices')
    op.drop_index('idx_instruments_type_currency', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_stablecoin', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_maturity', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_manager', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_issuer_type', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_issuer', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_isin', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_inception', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_esg_compliance', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_cusip', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_currency_asset', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_coingecko', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_bonds_maturity', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_bloomberg', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_asset_class', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_active_type', table_name='dim_financial_instruments')
    op.drop_index('idx_instruments_active_asset_class', table_name='dim_financial_instruments')
    op.drop_table('dim_financial_instruments')
    op.drop_table('dim_currencies')
    op.drop_table('dim_countries')
    # ### end Alembic commands ###
